import axios from "axios";
import { useState, useEffect, useRef } from "react";
import { Link } from "react-router-dom";
import "./Home.css";

export default function Home() {
  const [users, setUsers] = useState([]);
  const userName = useRef(null);
  const userEmail = useRef(null);

  // Fetch all users
  const getUsers = async () => {
    try {
      const { data } = await axios.get("http://localhost:8000/users");
      setUsers(data);
    } catch (error) {
      console.error("Error fetching users:", error);
    }
  };

  useEffect(() => {
    getUsers();
  }, []);

  // Create a new user (ID auto-generated by server)
  const createUser = async (e) => {
    e.preventDefault();
    const name = userName.current.value.trim();
    const email = userEmail.current.value.trim();
    if (!name || !email) return alert("Please fill in both fields.");

    try {
      await axios.post("http://localhost:8000/users", { name, email });
      getUsers();
      userName.current.value = "";
      userEmail.current.value = "";
    } catch (error) {
      console.error("Error creating user:", error);
    }
  };

  // Delete a user by ID
  const deleteUser = async (id) => {
    if (!window.confirm("Are you sure you want to delete this user?")) return;
    try {
      await axios.delete(`http://localhost:8000/users/${id}`);
      getUsers();
    } catch (error) {
      console.error("Error deleting user:", error);
    }
  };

  return (
    <div className="container">
      <div className="content">
        <form className="mainForm" onSubmit={createUser}>
          <p>Name</p>
          <input type="text" placeholder="User Name.." ref={userName} />

          <p>Email</p>
          <input type="email" placeholder="email.." ref={userEmail} />

          <input type="submit" value="Submit" />
        </form>

        <div className="table">
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Update</th>
                <th>Delete</th>
              </tr>
            </thead>
            <tbody>
              {users.map((user) => (
                <tr key={user.id}>
                  <td>{user.name}</td>
                  <td>{user.email}</td>
                  <td>
                    <Link to={`edit/${user.id}`}>
                      <button className="edit-btn">Edit</button>
                    </Link>
                  </td>
                  <td>
                    <button
                      className="delete-btn"
                      onClick={() => deleteUser(user.id)}
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
